argocd:
  enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  namespace: argocd
  values:
    imagePullPolicy: IfNotPresent
    repoServer:
      serviceAccount:
        automountServiceAccountToken: true
      volumeMounts:
      - name: custom-tools
        mountPath: /usr/local/bin/argocd-vault-plugin
        subPath: argocd-vault-plugin
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        env:
        - name: AVP_VERSION
          value: "1.12.0"
        args:
        - >-
          wget -O argocd-vault-plugin
          https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
    server:      
      config:
        configManagementPlugins: |-
          - name: argocd-vault-plugin
            generate:
              command: ["argocd-vault-plugin"]
              args: ["generate", "./"]
        repositories: |
          - type: helm
            name: stable
            url: https://charts.helm.sh/stable
          - type: helm
            name: argo-cd
            url: https://argoproj.github.io/argo-helm    
reflector:
  enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  namespace: reflector
  values:
    imagePullPolicy: IfNotPresent  
kubedashboard:
  enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  namespace: kubernetes-dashboard
  values:
    imagePullPolicy: IfNotPresent
    service:
      externalPort: 8080
    resources: 
      limits:
        cpu: 200m
kuma:
  enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  namespace: kuma-system
  values:
    imagePullPolicy: IfNotPresent