---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 4.9.11
    helm:
      releaseName: argocd
      version: v3
      valueFiles:
      - https://raw.githubusercontent.com/JarenDamm/argocd/main/non-prod/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.argoNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---