---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 4.9.11
    helm:
      releaseName: argocd
      version: v3
      {{- with .Values.argo.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.argoNamespace }}
  syncPolicy:
    {{- toYaml .Values.argo.syncPolicy | nindent 4 }}
---