{{- if .Values.linkerdViz.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-viz
    targetRevision: {{ .Values.linkerdViz.targetRevision | quote }}
    helm:
      releaseName: linkerd-viz
      version: v3
      {{- with .Values.linkerdViz.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-viz
  syncPolicy:
  {{- toYaml .Values.linkerdViz.syncPolicy | nindent 4 }}
  {{- with .Values.linkerdViz.ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}