{{ if and (.Values.linkerd.enabled) (.Values.linkerd.rotateCerts) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ca:
    secretName: linkerd-trust-anchor
{{- end }}