{{if .Values.reflector.enabled}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
spec:
  project: default
  source:
    chart: reflector
    repoURL: https://emberstack.github.io/helm-charts
    targetRevision: 6.1.47
    helm:
      releaseName: reflector
      version: v3
      {{- with .Values.reflector.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.reflector.namespace }}
  syncPolicy:
    {{- toYaml .Values.reflector.syncPolicy | nindent 4 }}
---
{{- end }}