apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.22.1
    helm:
      releaseName: vault
      version: v3
      valueFiles:
        - https://raw.githubusercontent.com/JarenDamm/argocd/main/vault/values.yaml      
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  syncPolicy:    
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true